potential:
  discrete:
    _target_: irc.distribution.BasicDiscretePotential
  continuous:
    _target_: irc.distribution.BasicContinuousPotential
param_net:
  discrete:
    _target_: irc.distribution.CompleteEmbedParamNet
  continous:
    _target_: null

estimate:
  num_epochs: 40
  batch_size: 64
  optimizer:
    _target_: torch.optim.SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 1.e-4
