dist_config:
  state: {}
  observation: {}

est_config:
  p_s:
    num_samples: 500
    num_epochs: 5
    batch_size: 32
    optimizer:
      lr: 0.05
  p_s_o:
    num_samples: 2000
  p_o_s:
    num_samples: 2000
