irc.distribution.BasicDiscretePotential.set_from_prob:
  eps: 1.e-4

irc.distribution.MultiLayerPerceptronParamNet:
  mlp_sizes: [128]

irc.distribution.CompleteEmbedParamNet:
  mlp_sizes: []

irc.distribution.BaseDistribution.estimate:
  num_epochs: 40
  lr: 0.01
  batch_size: 64

irc.distribution.ConditionalDistribution.estimate:
  num_epochs: 40
  lr: 0.01
  batch_size: 32

irc.model.BaseBeliefModel.run_one_episode:
  max_steps: 40

irc.model.ReplayBuffer:
  capacity: 1000

irc.model.BeliefNet:
  mlp_features: [32]

irc.model.SamplingBeliefModel:
  update_config:
    num_samples: 400
    num_epochs: 40
    lr: 0.005
    batch_size: 32

irc.model.SamplingBeliefModel.estimate_p_s_o:
  num_samples: 1000

irc.model.SamplingBeliefModel.estimate_p_o_s:
  num_samples: 5000
  use_replay: true

irc.model.SamplingBeliefModel.collect_rollouts:
  num_steps: 500
  max_steps: 50

irc.model.SamplingBeliefModel.train_belief_net:
  mse_reg: 0.1
  num_epochs: 100
  lr: 0.01
  batch_size: 64

irc.manager.AgentManager:
  defaults:
    env:
      _target_: null
    env_param: null
    seed: 0
    model:
      _target_: irc.model.SamplingBeliefModel
    algo:
      _target_: stable_baselines3.PPO
      gamma: 0.99
    policy:
      _target_: MlpPolicy
    learn:
      rl_steps: 1024
  eval_config:
    num_episodes: 40
    max_steps: 60
  device: cpu
  to_check_env: false
  eval_interval: 2
  save_interval: 1
  disp_interval: 5

defaults.SamplingBeliefModel:
  estimate:
    p_s_o: {}
    p_o_s:
      init: {use_replay: false}
      tune: {num_samples: 100, lr: 0.005}
  collect:
    init: {max_steps: 20}
    tune: {num_steps: 100}
  train:
    init: {batch_size: 32}
    tune: {num_epochs: 5}

irc.manager.IRCManager:
  device: cpu

irc.manager.IRCManager.train_agent:
  num_epochs: 30

irc.manager.AgentManager.train_agent:
  num_epochs: 30

irc.manager.IRCManager.sweep:
  agent_seeds: [0, 1, 2, 3, 4, 5, 6, 7]
