distribution:
  BasicDiscretePotential:
    set_from_prob:
      eps: 1.e-4
  BaseDistribution:
    estimate:
      l2_reg: 0.001
      lr: 0.01
      num_epochs: 40
      batch_size: 64
  _create_potential:
    discrete:
      _target_: irc.distribution.BasicDiscretePotential
    continuous:
      _target_: irc.distribution.BasicContinuousPotential
  _create_distribution:
    discrete:
      _target_: irc.distribution.BasicDiscreteDistribution
    continuous:
      _target_: irc.distribution.BasicContinuousDistribution

net:
  BaseDistributionNet:
    _train:
      l2_reg: 0.001
      lr: 0.01
      num_epochs: 40
      batch_size: 32
  _create_net:
    _target_: irc.net.MultiLayerPerceptronNet
  MultiLayerPerceptronNet:
    _init_:
      _expanse: 16 # default expansion for one-hidden layer

model:
  BaseBeliefModel:
    run_one_episode:
      max_steps: 40
  NetworkBeliefModel:
    _init_:
      action_depend: false
  SamplingBeliefModel:
    _init_:
      buffer_cap: 1000
    train_init_net:
      num_samples: 1000
    train_observe_net:
      num_samples: 5000
      use_replay: true
    collect_rollouts:
      total_steps: 400
      max_steps: 40
      update_config:
        num_samples: 400
        num_epochs: 40
        lr: 0.005
        batch_size: 32
    train_update_net:
      l2_reg: 0.001
      lr: 0.01
      num_epochs: 100
      batch_size: 64
  DistilledBeliefModel:
    train_init_net:
      num_epochs: 80
    train_update_net:
      num_epochs: 60

agent:
  DistilledBeliefAgent:
    set_env_param:
      gamma: 0.99
      ent_coef: 0.01
    train_policy_net:
      num_epochs: 60
    sga_inference:
      lr: 0.002
      momentum: 0.8
      num_steps: 200

manager:
  AgentManager:
    _init_:
      defaults:
        env:
          _target_: null
        task:
          gamma: 0.99
          ent_coef: 0.01
        env_param: null
        seed: 0
        model:
          _target_: irc.model.SamplingBeliefModel
        algo:
          _target_: stable_baselines3.PPO
        policy:
          _target_: MlpPolicy
        learn:
          rl_steps: 1024
      eval_config:
        total_steps: 2400
        max_steps: 60
      device: cpu
      to_check_env: false
      eval_interval: 2
      save_interval: 1
      disp_interval: 5
    get_config:
      _sampling:
        train:
          init_net: {}
          observe_net:
            init: {use_replay: false}
            tune: {num_samples: 100, lr: 0.005}
          update_net:
            init: {batch_size: 32}
            tune: {num_epochs: 5}
        collect:
          init: {max_steps: 20}
          tune: {total_steps: 100}
    train_agent:
      num_epochs: 30
    train_agents:
      num_epochs: 30
    _grid2configs:
      seeds: [0, 1, 2, 3, 4, 5, 6, 7]
    find_agents:
      min_epoch: 30
    distill_agents:
      total_steps: 100
      max_steps: 20
      to_train: ['I', 'U', 'P']
    compare_agents:
      total_steps: 100
      max_steps: 20

tqdm_kw:
  bar_format: '{desc:18} {percentage:3.0f}%|{bar:50}{r_bar}'
  ascii: True
